#!/bin/bash

if [ "$(id -u)" = "0" ]; then
   echo "Please run this script under the ethereum user account. Type: su - ethereum and launch the script again" 1>&2
   exit 1
fi

git clone https://github.com/raiden-network/raiden.git
cd raiden
pip install -c constraints.txt --upgrade -r requirements-dev.txt
sudo python setup.py develop

exit 0
