#!/bin/bash

if [ "$(id -u)" = "0" ]; then
   echo "Please run this script under the ethereum user account. Type: su - ethereum and try again" 1>&2
   exit 1
fi

sudo apt-get -y install libpq-dev libjpeg-dev python3-pip python3-setuptools libgcc1-arm64-cross python3-dev libffi-dev python3-wheel libgmp-dev pkg-config zlib1g-dev
cd ~
git clone https://github.com/raiden-network/raiden.git
cd ~/raiden
pip3 install -c constraints.txt --upgrade -r requirements-dev.txt
sudo python3 setup.py develop

exit 0

